riccardoperra/codeimage

- .changeset/ninety-plants-count.md
- apps/codeimage/src/components/LeftSidebar/EditorStyleForm.tsx
- apps/codeimage/src/components/ui/Select/Select.css.ts
- apps/codeimage/src/components/ui/Select/Select.tsx
- apps/codeimage/src/core/configuration.ts
```
[X] Bugfix
[X] Feature
```
Native input select on mobile modality
```
[ ] Yes
[X] No
```
linked with #56
closes #66
> 66 editor select dropdown overflow broken in mobile view

- .changeset/healthy-crews-count.md
- packages/config/src/lib/base/themes.ts
- packages/theme/src/lib/themes/material-palenight/index.ts
- packages/theme/src/lib/themes/material-palenight/material-palenight.ts
- packages/theme/src/public-api.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: resolves #23 
```
[ ] Yes
[X] No
```
> feat: 23 material palenight theme

- .changeset/itchy-rats-work.md
- apps/codeimage/package.json
- apps/codeimage/src/components/Footer/Footer.tsx
- apps/codeimage/src/components/TerminalControlField/TerminalControlField.tsx
- apps/codeimage/src/hooks/use-tab-icon.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: resolves #101
```
[ ] Yes
[X] No
```
> fix: 101 fix footer links

- .changeset/rich-cooks-jump.md
- packages/config/src/lib/base/languages.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: resolves #108 
```
[ ] Yes
[X] No
```
> 108 missing ng component icon

- .changeset/honest-planets-explain.md
- apps/codeimage/src/components/KeyboardShortcuts/KeyboardShortcuts.tsx
- apps/codeimage/src/components/ThemeSwitcher/ThemeSwitcher.tsx
- apps/codeimage/src/i18n/index.ts
- package.json
```
[ ] Bugfix
[X] Feature
```
Issue Number: resolves #88 
```
[ ] Yes
[X] No
```
> feat: 88 theme search input

- .changeset/perfect-cars-retire.md
- apps/codeimage/src/components/Icons/CheckCircle.tsx
- apps/codeimage/src/components/Icons/EmptyCircle.tsx
- apps/codeimage/src/components/Scaffold/Sidebar/Sidebar.css.ts
- apps/codeimage/src/components/ThemeSwitcher/ThemeBox.tsx
- apps/codeimage/src/components/ThemeSwitcher/ThemeSwitcher.css.ts
- apps/codeimage/src/components/ThemeSwitcher/ThemeSwitcher.tsx
- apps/codeimage/src/components/ui/SvgIcon/SvgIcon.css.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: resolves #113 
```
[X] Yes
[ ] No
```
> feat: 113 improve style for selected theme in sidebar

- .changeset/fluffy-pans-roll.md
- apps/codeimage/src/App.tsx
- apps/codeimage/src/components/Terminal/TabIcon.tsx
- apps/codeimage/src/components/Terminal/TerminalHost.tsx
- apps/codeimage/src/components/Terminal/macOS/MacOsTerminal.tsx
- apps/codeimage/src/components/Terminal/windows/WindowsTerminal.tsx
- apps/codeimage/src/components/ui/SvgIcon/SvgExternalIcon.tsx
- apps/codeimage/src/index.tsx
- apps/codeimage/src/state/effect.ts
- apps/codeimage/src/sw.ts
- apps/codeimage/vite.config.ts
- packages/config/package.json
- packages/config/src/lib/base/languages.ts
- packages/config/src/lib/types/language-def.ts
- pnpm-lock.yaml
```
[ ] Bugfix
[X] Feature
```
Issue Number: resolves #109 
```
[ ] Yes
[ ] No
```
> feat: 109 improve tab svg loader icon

- .changeset/sour-oranges-glow.md
- apps/codeimage/src/index.tsx
- packages/locale/package.json
- packages/locale/src/lib/use-i18n.ts
- packages/locale/src/public-api.ts
- pnpm-lock.yaml
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
Issue Number: resolves #87 
```
[ ] Yes
[X] No
```
> refactor(locale): 87 replace in with solid primitives package

- .changeset/cool-garlics-jump.md
- apps/codeimage/src/components/LeftSidebar/EditorStyleForm.tsx
- apps/codeimage/src/components/LeftSidebar/FrameStyleForm.tsx
- apps/codeimage/src/components/LeftSidebar/WindowStyleForm.tsx
- apps/codeimage/src/components/ui/Dropdown/Dropdown.css.ts
- apps/codeimage/src/i18n/index.ts
- apps/codeimage/src/i18n/sidebar.ts
- packages/config/src/lib/base/locales.ts
```
[ ] Bugfix
[X] Feature
```
Issue Number: #71 
```
[ ] Yes
[X] No
```
> feat: 71 add german language

- .changeset/long-plants-sparkle.md
- packages/theme/src/lib/themes/coldark/coldark-dark.ts
- packages/theme/src/lib/themes/duotone-dark/duotone-dark.ts
- packages/theme/src/lib/themes/duotone-sea/duotone-sea.ts
- packages/theme/src/lib/themes/holi/holi.ts
- packages/theme/src/lib/themes/material-palenight/material-palenight.ts
- packages/theme/src/lib/themes/night-owl/night-owl.ts
- packages/theme/src/lib/themes/vscode-dark/vscode-dark.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: resolves #116 
```
[ ] Yes
[X] No
```
> fix: 116 editor cursor not visible for some themes

- .changeset/kind-insects-act.md
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- apps/codeimage/src/components/ui/RangeField/RangeField.css.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: resolves #95 
```
[ ] Yes
[X] No
```
> fix: 95 broken range input on firefox

- apps/codeimage/src/App.tsx
- apps/codeimage/src/components/LeftSidebar/FrameStyleForm.tsx
- apps/codeimage/src/core/store/elf-auto-setters-factory.ts
- apps/codeimage/src/core/store/use-effect.ts
- apps/codeimage/src/state/editor.ts
- apps/codeimage/src/state/frame.ts
- apps/codeimage/src/state/terminal.ts
- apps/codeimage/src/state/ui.ts
- packages/config/src/lib/base/languages.ts
```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
```
Issue Number: resolves #131 
```
[ ] Yes
[X] No
```
> refactor: add elf setter props factory

- .changeset/nice-waves-roll.md
- apps/codeimage/src/components/Frame/Frame.css.ts
- apps/codeimage/src/components/Frame/Frame.tsx
- apps/codeimage/src/components/Frame/FrameHandler.tsx
- apps/codeimage/src/core/hooks/resizable.ts
- pnpm-lock.yaml
```
[X] Bugfix
[ ] Feature
```
Issue Number: resovles #105 
```
[ ] Yes
[X] No
```
> fix: 105 fix editor frame size and resizing

- packages/config/package.json
- packages/theme/package.json
- pnpm-lock.yaml
```
[X] Bugfix
[ ] Feature
```
Issue Number: resolves #134
```
[ ] Yes
[ ] No
```
> fix: fix codemirror dependency version

- package.json
```
[ ] Bugfix
[ ] Feature
```
Issue Number: resolves #107
```
[ ] Yes
[X] No
```
> chore: fix build library script

- .changeset/wet-trains-boil.md
- apps/codeimage/src/components/LeftSidebar/EditorStyleForm.tsx
- apps/codeimage/src/components/LeftSidebar/FrameStyleForm.tsx
- apps/codeimage/src/components/LeftSidebar/WindowStyleForm.tsx
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- apps/codeimage/src/i18n/index.ts
- commitlint.config.js
```
[X] Bugfix
[ ] Feature
```
Issue Number: #138 
```
[ ] Yes
[X] No
```
> fix: export dialog translations not updating #138

- apps/codeimage/public/sitemap.xml
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
```
[X] Yes
[ ] No
```
> chore: add sitemap.xml

- .changeset/twenty-colts-train.md
- apps/codeimage/src/components/LoadingOverlay/LoadingOverlay.css.ts
- apps/codeimage/src/components/LoadingOverlay/LoadingOverlay.tsx
- apps/codeimage/src/components/PropertyEditor/EditorForm.tsx
- apps/codeimage/src/components/PropertyEditor/EditorSidebar.css.ts
- apps/codeimage/src/components/Terminal/TabName.tsx
- apps/codeimage/src/components/Terminal/macOS/MacOsTerminal.tsx
- apps/codeimage/src/components/Terminal/terminal.css.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: closes #103 
```
[ ] Yes
[X] No
```
> fix: tab icon loading is not visible on light mode editor #103

- .changeset/stale-dots-travel.md
- apps/codeimage/src/components/Icons/Download.tsx
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- apps/codeimage/src/core/constants/browser.ts
- apps/codeimage/src/hooks/use-export-image.ts
- apps/codeimage/src/theme/dark-theme.css.ts
- apps/codeimage/src/ui/Toast/Snackbar.tsx
```
[X] Bugfix
[ ] Feature
```
Issue Number: closes #159 
```
[ ] Yes
[X] No
```
> fix: export button loading state stuck on iOS #159 

- .changeset/red-sheep-cheat.md
- apps/codeimage/src/components/Terminal/macOS/MacOsTerminal.tsx
- apps/codeimage/src/components/Terminal/terminal.css.ts
- apps/codeimage/src/components/Terminal/windows/WindowsTerminal.css.ts
- apps/codeimage/src/components/Terminal/windows/WindowsTerminal.tsx
- apps/codeimage/src/core/directives/exportExclude.ts
- apps/codeimage/src/hooks/use-export-image.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: closes #162 
```
[ ] Yes
[X] No
```
> fix: hidden tab accent and placeholder on export when empty #162

- .changeset/breezy-turtles-invent.md
- apps/codeimage/src/components/Terminal/terminal.css.ts
- apps/codeimage/src/components/Terminal/windows/WindowsTerminal.tsx
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> fix: fix mac os terminal style margin

- .changeset/four-mugs-kick.md
- packages/theme/src/lib/plugins/autocomplete-style.ts
- packages/theme/src/lib/themes/coldark/index.ts
- packages/theme/src/lib/themes/duotone-dark/index.ts
- packages/theme/src/lib/themes/duotone-sea/index.ts
- packages/theme/src/lib/themes/holi/index.ts
- packages/theme/src/lib/themes/material-ocean/vs.ts
- packages/theme/src/lib/themes/material-palenight/index.ts
- packages/theme/src/lib/themes/night-owl/index.ts
- packages/theme/src/lib/themes/vscode-dark/index.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #167
```
[ ] Yes
[X] No
```
> fix: broken editor autocomplete style #167

- .changeset/dull-rules-drop.md
- apps/codeimage/src/App.tsx
- apps/codeimage/src/components/PromptUpdate/PromptUpdate.tsx
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- packages/ui/src/lib/primitives/Snackbar/Snackbar.css.ts
- packages/ui/src/lib/primitives/Snackbar/Snackbar.tsx
- packages/ui/src/lib/primitives/Snackbar/SnackbarHost.tsx
- packages/ui/src/lib/primitives/Snackbar/index.ts
- packages/ui/src/lib/primitives/Snackbar/snackbar.store.ts
- packages/ui/src/lib/primitives/index.ts
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
Issue Number: closes #186 
```
[ ] Yes
[ ] No
```
> refactor(ui): move Snackbar to @codeimage/ui

- README.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update README.md

- .changeset/spicy-spoons-repeat.md
- apps/codeimage/src/components/ThemeSwitcher/ThemeSwitcher.tsx
```
[X} Bugfix
[ ] Feature
```
Issue Number: closes #199 
```
[ ] Yes
[ ] No
```
> fix(app): add click event to ThemeSwitcher radio item

- .changeset/wild-boxes-allow.md
- apps/codeimage/src/hooks/use-export-image.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #203 
```
[ ] Yes
[X] No
```
> fix(app): fix broken padding on image export

- packages/config/src/lib/base/editor-basic-setup.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #217 
```
[ ] Yes
[X] No
```
> fix(config): add editor indentWithTab keymap

- .changeset/healthy-apricots-act.md
- apps/codeimage/src/components/Toolbar/ShareButton.tsx
```
[X] Bugfix
[ ] Feature
```
Issue Number: closes #220 
```
[ ] Yes
[X] No
```
> fix(app): fix disabled ShareButton on MacOSX

- .changeset/cyan-boxes-hope.md
- apps/codeimage/index.html
- apps/codeimage/src/core/configuration/font.ts
```
[ ] Bugfix
[X] Feature
```
```
[ ] Yes
[ ] No
```
> feat(app): add space mono font

- apps/codeimage/src/App.tsx
- apps/codeimage/src/sw.ts
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[ ] No
```
> refactor(app): sw refactor with claims and auto update

- .changeset/six-weeks-pump.md
- apps/codeimage/public/assets/blank.html
- apps/codeimage/src/hooks/use-export-image.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #230 
```
[ ] Yes
[X] No
```
> fix(app): open button doesnt work on safari

- apps/codeimage/src/hooks/use-export-image.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(app): improve export image open tab on ios

- apps/codeimage/src/core/constants/umami.ts
- apps/codeimage/vite.config.ts
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: fix umami script

- .changeset/itchy-maps-drive.md
- apps/codeimage/src/components/BottomBar/BottomBar.tsx
- apps/codeimage/src/i18n/bottombar.ts
- apps/codeimage/src/i18n/index.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: #207 
the bottom it'not more hardcoded but use i18n strategy
```
[ ] Yes
[ x] No
```
https://github.com/riccardoperra/codeimage/issues/207
> fix(app): added i18n bottombar

- apps/codeimage/src/App.tsx
- apps/codeimage/src/components/CustomEditor/CustomEditor.tsx
- apps/codeimage/src/components/Terminal/MacOsTerminal/MacOsTerminal.tsx
- apps/codeimage/src/components/Terminal/Tabs/Tab/Tab.css.ts
- apps/codeimage/src/components/Terminal/Tabs/TerminalWindowTabList.tsx
- apps/codeimage/src/components/Terminal/Tabs/createTabTheme.ts
- apps/codeimage/src/components/Terminal/TerminalHost.tsx
- apps/codeimage/src/components/Terminal/WindowsTerminal/WindowsTerminal.tsx
- apps/codeimage/src/components/Terminal/terminal.css.ts
- apps/codeimage/src/components/TerminalControlField/TerminalControlField.tsx
- apps/codeimage/src/components/ThemeSwitcher/ThemeSwitcher.tsx
- apps/codeimage/src/state/editor/createEditorOptions.ts
- apps/codeimage/src/state/editor/createEditors.ts
- packages/theme/src/lib/core/custom-theme.ts
- packages/theme/src/lib/themes/coldark/index.ts
- packages/theme/src/lib/themes/light/theme.ts
- packages/theme/src/lib/themes/material-light/index.ts
- packages/theme/src/lib/themes/material-ocean/index.ts
- packages/theme/src/lib/themes/material-ocean/theme.ts
- packages/theme/src/lib/themes/material-volcano/index.ts
- packages/theme/src/lib/themes/material-volcano/materialVolcano.ts
- packages/theme/src/lib/themes/night-owl/index.ts
- packages/theme/src/lib/themes/synthwave84/index.ts
- packages/theme/src/lib/themes/synthwave84/synthwave84.ts
- packages/theme/src/lib/themes/vscode-dark/index.ts
- packages/theme/src/lib/themes/vscode-dark/vscode-dark.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #257 
```
[ ] Yes
[ ] No
```
> fix: add custom theme tab color options

- .changeset/kind-zebras-provide.md
- .changeset/many-dolphins-jog.md
- apps/codeimage/src/state/theme/themeRegistry.ts
- commitlint.config.js
- packages/highlight/package.json
- packages/highlight/rollup.config.ts
- packages/highlight/src/lib/themes/githubDark/githubDark.ts
- packages/highlight/src/lib/themes/githubDark/index.ts
- packages/highlight/src/lib/themes/githubLight/githubLight.ts
- packages/highlight/src/lib/themes/githubLight/index.ts
- packages/highlight/src/lib/themes/index.ts
- pnpm-lock.yaml
```
[ ] Bugfix
[X] Feature
```
```
[ ] Yes
[ ] No
```
> feat(highlight): add Github themes

- apps/codeimage/src/components/PropertyEditor/WindowStyleForm.tsx
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(app): fix mobile shadow select

- apps/codeimage/src/components/Scaffold/Scaffold.css.ts
- packages/ui/src/lib/theme/base.css.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(app): fix mobile bottombar

- packages/config/src/lib/base/colors.ts
- packages/highlight/src/lib/themes/poimandres/poimandres.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(config): fix gradients

- apps/codeimage/src/components/Scaffold/Scaffold.css.ts
- apps/codeimage/src/components/Toolbar/Toolbar.css.ts
- apps/codeimage/src/pages/Editor/App.css.ts
- apps/codeimage/src/pages/Editor/Editor.tsx
- apps/codeimage/src/state/editor/createEditorInit.ts
- apps/codeimage/src/state/editor/editor.ts
- apps/codeimage/src/state/editor/frame.ts
- apps/codeimage/src/state/editor/model.ts
- apps/codeimage/src/state/editor/terminal.ts
- Automatically redirect user to last updated editor when accessing the root url /
> feat(app): project editor redirect

- .changeset/famous-adults-attend.md
- .changeset/mean-baboons-rule.md
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- apps/codeimage/src/components/Toolbar/ExportNewTabButton.tsx
- packages/ui/src/lib/primitives/Button/Button.css.ts
- packages/ui/src/lib/primitives/Button/Button.tsx
- packages/ui/src/lib/primitives/Icon/SvgIcon.tsx
- packages/ui/src/lib/primitives/Loader/LoadingCircle.css.ts
- packages/ui/src/lib/primitives/Loader/LoadingCircle.tsx
- packages/ui/src/lib/primitives/Loader/index.ts
> fix(app): add loading indicator when exporting as image

- packages/config/package.json
- packages/config/src/lib/base/languages.ts
- pnpm-lock.yaml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(config): add xml and json language support

- .changeset/serious-berries-lick.md
- apps/codeimage/src/components/Icons/DotVertical.tsx
- apps/codeimage/src/components/KeyboardShortcuts/KeyboardShortcuts.tsx
- apps/codeimage/src/components/Toolbar/SettingsDialog.tsx
- apps/codeimage/src/components/Toolbar/ShareButton.tsx
- apps/codeimage/src/components/Toolbar/Toolbar.tsx
- apps/codeimage/src/components/Toolbar/ToolbarSettings.tsx
- apps/codeimage/src/pages/Dashboard/components/ProjectItem/ProjectItem.tsx
- packages/ui/src/lib/primitives/Button/Button.css.ts
- packages/ui/src/lib/primitives/Button/Button.tsx
- packages/ui/src/lib/primitives/IconButton/IconButton.css.ts
- packages/ui/src/lib/primitives/IconButton/IconButton.tsx
- packages/ui/src/lib/primitives/IconButton/index.tsx
- packages/ui/src/lib/primitives/index.ts
> feat(ui): add icon button

- apps/codeimage/src/index.tsx
- apps/codeimage/src/pages/Dashboard/Dashboard.css.ts
- apps/codeimage/src/pages/Dashboard/components/DashboardHeader/DashboardHeader.css.ts
- apps/codeimage/src/pages/Dashboard/components/DashboardHeader/DashboardHeader.tsx
- apps/codeimage/src/pages/Dashboard/components/ProjectItem/ProjectItem.css.ts
- apps/codeimage/src/pages/Dashboard/components/ProjectList/ProjectList.css.ts
> refactor(app): dashboard style improvements

- .github/workflows/main.yml
- apps/api/package.json
- apps/api/test/tsconfig.json
- tsconfig.json
> refactor: replace node with tsx

- apps/codeimage/src/core/store/trackContext.ts
- apps/codeimage/src/data-access/project.ts
- apps/codeimage/src/state/editor/createEditorInit.ts
- apps/codeimage/src/state/editor/editor.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: autosave state update synchronization

- .changeset/tiny-bees-divide.md
- packages/dom-export/package.json
- packages/dom-export/src/lib/applyStyleFromOptions.ts
- packages/dom-export/src/lib/cloneNode.ts
- packages/dom-export/src/lib/embedImages.ts
- packages/dom-export/src/lib/embedResources.ts
- packages/dom-export/src/lib/getBlobFromURL.ts
- packages/dom-export/src/lib/index.ts
- packages/dom-export/src/lib/util.ts
- pnpm-lock.yaml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: disable shadow rendering on exported image in ios

- apps/api/src/app.ts
- apps/api/src/plugins/cors.ts
- apps/api/src/server.ts
- scripts/make-env.ts
> fix: backend dynamic cors

- apps/codeimage/src/components/BottomBar/BottomBar.css.ts
- apps/codeimage/src/components/BottomBar/BottomBar.tsx
- apps/codeimage/src/components/Scaffold/Scaffold.tsx
- apps/codeimage/src/components/Terminal/Tabs/Tab/Tab.css.ts
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- apps/codeimage/src/components/Toolbar/ExportNewTabButton.tsx
- apps/codeimage/src/components/Toolbar/ShareButton.tsx
- apps/codeimage/src/components/Toolbar/Toolbar.css.ts
- apps/codeimage/src/components/Toolbar/Toolbar.tsx
- apps/codeimage/src/components/Toolbar/ToolbarSnippetName.tsx
- apps/codeimage/src/index.tsx
- apps/codeimage/src/pages/Dashboard/Dashboard.css.ts
- apps/codeimage/src/pages/Dashboard/components/CreateNewProjectButton/CreateNewProjectButton.tsx
- apps/codeimage/src/pages/Dashboard/components/ProjectItem/ProjectItem.tsx
- apps/codeimage/src/pages/Dashboard/components/ProjectToolbar/ProjectToolbar.css.ts
- apps/codeimage/src/pages/Dashboard/components/ProjectToolbar/ProjectToolbar.tsx
- apps/codeimage/src/pages/Editor/App.css.ts
- apps/codeimage/src/pages/Editor/App.tsx
- apps/codeimage/src/pages/Editor/components/EditorSkeleton.tsx
- apps/codeimage/src/pages/NotFound/NotFoundPage.css.ts
- apps/codeimage/src/theme/dark-theme.css.ts
- apps/codeimage/src/ui/GithubLoginButton/GithubLoginButton.tsx
- packages/ui/dev/demo/Button.tsx
- packages/ui/src/lib/primitives/Box/Stack.tsx
- packages/ui/src/lib/primitives/Button/Button.css.ts
- packages/ui/src/lib/primitives/IconButton/IconButton.css.ts
- packages/ui/src/lib/primitives/IconButton/IconButton.tsx
- packages/ui/src/lib/primitives/Link/Link.tsx
- packages/ui/src/lib/primitives/TextField/TextField.css.ts
- packages/ui/src/lib/theme/base.css.ts
> feat: add experimental mobile ui

- .changeset/sweet-spies-grab.md
- .vscode/settings.json
- packages/highlight/package.json
- packages/highlight/src/lib/themes/index.ts
- packages/highlight/src/lib/themes/panda/index.ts
- packages/highlight/src/lib/themes/panda/panda.ts
- pnpm-lock.yaml
```
[ ] Bugfix
[X] Feature
```
Issue Number: Closes #366
```
[ ] Yes
[X] No
```
> Feat: panda theme

- .changeset/nervous-rats-judge.md
- packages/highlight/package.json
- packages/highlight/src/lib/themes/index.ts
- packages/highlight/src/lib/themes/shadeOfPurple/index.ts
- packages/highlight/src/lib/themes/shadeOfPurple/shadeOfPurple.ts
Addition of shades Of Purple theme
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
https://github.com/riccardoperra/codeimage/issues/365
> feat: shades of purple theme

- .changeset/empty-apples-itch.md
- packages/highlight/package.json
- packages/highlight/src/lib/themes/index.ts
- packages/highlight/src/lib/themes/moonlight/index.ts
- packages/highlight/src/lib/themes/moonlight/moonlight.ts
This to add moonlight theme.
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/riccardoperra/codeimage/issues/20
```
[ ] Yes
[ ] No
```
> feat: added moonlight theme

- .github/workflows/main.yml
- .github/workflows/prod-deploy.yml
- README.md
- apps/codeimage/src/state/auth/auth0.ts
> chore: update README.md

- apps/codeimage/src/state/theme/themeRegistry.ts
- packages/highlight/src/lib/themes/vitesseDark/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: added vitesseDark to themeRegistry

- packages/config/src/lib/base/languages.ts
- packages/config/src/lib/icons/txt.svg
- scripts/patch-solid-exports.ts
> feat: add txt extension to disable syntax highlighting

- apps/codeimage/src/index.tsx
- apps/website/src/components/Header/Header.tsx
- apps/website/src/core/hydration/schedule.ts
- apps/website/src/core/hydration/strategy.ts
- apps/website/src/ui.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(website): login by redirect state

- .changeset/red-timers-pay.md
- apps/codeimage/src/index.tsx
- apps/codeimage/src/theme/global.css.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(app): fix light mode

- apps/codeimage/index.html
- apps/website/src/components/Landing/EditorSteps/EditorScene/TwitterCard/TwitterCard.css.ts
- apps/website/src/components/Landing/EditorSteps/EditorScene/TwitterCard/TwitterCard.tsx
- apps/website/src/components/Main/MainPage.tsx
- apps/website/src/core/hydration/createHydration.ts
- apps/website/src/root.tsx
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: fix copy

- .changeset/eleven-buckets-walk.md
- apps/codeimage/index.html
- apps/codeimage/src/core/configuration/font.ts
```
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
> feat: added Cascadia Code font

- .changeset/wise-mugs-impress.md
- apps/codeimage/src/components/PropertyEditor/WindowStyleForm.tsx
- apps/codeimage/src/state/editor/terminal.ts
> fix(app): set shadow none not working

- .changeset/sweet-horses-shave.md
- apps/codeimage/src/components/PropertyEditor/EditorStyleForm.tsx
- apps/codeimage/src/components/PropertyEditor/WindowStyleForm.tsx
- apps/codeimage/src/components/Terminal/TerminalHost.tsx
- apps/codeimage/src/components/ThemeSwitcher/ThemeSwitcher.tsx
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- apps/codeimage/src/components/Toolbar/LanguageSelectorButton.tsx
- apps/codeimage/src/components/Toolbar/SettingsDialog.tsx
- apps/codeimage/src/core/constants/umami.ts
- apps/codeimage/src/index.tsx
- apps/codeimage/src/state/effects/onCopyToClipboard.tsx
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: umami is not defined for some browsers

- .changeset/silver-trees-sing.md
- apps/codeimage/src/components/CustomEditor/CustomEditor.tsx
- packages/config/src/lib/base/languages.ts
- packages/config/src/lib/types/language-def.ts
> feat(app/config): vue highlighting support

- package.json
- pnpm-lock.yaml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: force solid version to 1.6.3

- .changeset/fuzzy-pants-study.md
- apps/codeimage/src/state/editor/activeEditor.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(app): change file extension on language change

- .changeset/gold-weeks-trade.md
- packages/dom-export/src/lib/embedWebFonts.ts
> fix(dom-export): cannot load font style value on firefox

- .changeset/clean-seahorses-serve.md
- apps/codeimage/src/data-access/client.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(app): remove login auto-redirect on api without auth

- apps/codeimage/package.json
- apps/codeimage/src/index.tsx
- apps/codeimage/src/state/editor/editor.ts
- apps/codeimage/src/state/editor/frame.ts
- apps/codeimage/src/state/editor/index.ts
- apps/codeimage/src/state/editor/terminal.ts
- apps/codeimage/src/state/index.ts
- package.json
- packages/atomic-state/package.json
- packages/atomic-state/src/experimental/commands/fluent.ts
- packages/atomic-state/src/experimental/commands/index.ts
- packages/atomic-state/src/index.tsx
- pnpm-lock.yaml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: move to statebuilder

- .changeset/green-pumpkins-taste.md
- packages/config/src/lib/base/languages.ts
> feat(config): add support for shell, dockerfile, swift

- .changeset/clean-poems-crash.md
- packages/config/src/lib/base/languages.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: 463
```
[ ] Yes
[x] No
```
> feat(config): added csharp

- .changeset/short-turtles-hug.md
- apps/codeimage/src/state/editor/editor.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(app): fix editor state options persistence after refresh

- .changeset/pink-jobs-remain.md
- packages/ui/src/lib/hooks/pagination/getLastPage.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(ui): fix pagination total pages calc

- .changeset/four-mangos-burn.md
- apps/api/prisma/migrations/20230302182841_project_unique_owner_constraint_336_feature/migration.sql
- apps/api/prisma/migrations/20230302183231_editor_add_ligatures_option/migration.sql
- apps/api/prisma/schema.prisma
- apps/api/src/modules/project/infra/prisma/prisma-project.repository.ts
- apps/api/src/modules/project/mapper/create-project-mapper.ts
- apps/api/src/modules/project/mapper/get-project-by-id-mapper.ts
- apps/api/src/modules/project/schema/project-create.schema.ts
- apps/api/src/modules/project/schema/project-update.schema.ts
- apps/api/src/modules/project/schema/project.schema.ts
- apps/api/test/modules/project/mapper/create-project-mapper.test.ts
- apps/api/test/modules/project/mapper/get-project-by-id-mapper.test.ts
- apps/api/test/modules/project/service/project.service.test.ts
- apps/api/test/routes/v1/project/create.integration.test.ts
- apps/api/test/routes/v1/project/update.integration.test.ts
- apps/codeimage/src/components/CustomEditor/CustomEditor.tsx
- apps/codeimage/src/components/PropertyEditor/EditorStyleForm.tsx
- apps/codeimage/src/i18n/sidebar.ts
- apps/codeimage/src/state/editor/editor.ts
- apps/codeimage/src/state/editor/model.ts
> feat(app): option to disable ligatures in fonts #483

- .changeset/grumpy-socks-scream.md
- apps/api/src/app.ts
- apps/api/src/common/exceptions/UnprocessableEntityException.ts
- apps/api/src/modules/preset/exceptions/ExceedPresetLimitException.ts
- apps/api/src/modules/preset/handlers/create.ts
- apps/api/src/modules/preset/handlers/index.ts
- apps/api/src/modules/preset/index.ts
- apps/api/src/modules/preset/repository/preset.repository.ts
- apps/api/src/modules/preset/repository/prisma-preset.repository.ts
- apps/api/src/plugins/errorHandler.ts
- apps/api/test/modules/preset/handlers/create.test.ts
- apps/api/test/modules/preset/handlers/dependencies.ts
- apps/api/test/modules/preset/handlers/findById.test.ts
- apps/api/test/modules/preset/handlers/getAll.test.ts
- apps/api/test/modules/preset/mapper/presetMapper.test.ts
- apps/api/test/routes/v1/preset/create.integration.test.ts
add preset limit.
To add for deploy:
```env
PRESET_LIMIT=20
```
> feat(api): add configurable preset limit

- apps/api/src/routes/v1/preset/delete.ts
- apps/codeimage/src/components/BottomBar/BottomBar.tsx
- apps/codeimage/src/components/Icons/CloudIcon.tsx
- apps/codeimage/src/components/ThemeSwitcher/PresetSwitcher.css.ts
- apps/codeimage/src/components/ThemeSwitcher/PresetSwitcher.tsx
- apps/codeimage/src/data-access/preset.ts
- apps/codeimage/src/state/plugins/bindStateBuilderResource.ts
- apps/codeimage/src/state/plugins/withEntityPlugin.ts
- apps/codeimage/src/state/plugins/withIndexedDbPlugin.ts
- apps/codeimage/src/state/presets/bridge.ts
- apps/codeimage/src/state/presets/presets.ts
- apps/codeimage/src/state/presets/types.ts
> feat(app): offline presets

- CONTRIBUTING.md
- Docs
- I have setup the repo and I found an old version command of the docker compose, as defined [here](https://docs.docker.com/compose/) since January the v1 is not more supported.
- I have checked for the listed command and I realized checking in `package.json` history that the current one is obsolete, so I updated it
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
```
[ ] Yes
[X] No
```
> feat(doc):update contributing docker command

- apps/codeimage/src/components/Presets/PresetUpdateDialog.tsx
- apps/codeimage/src/components/Terminal/MacOsTerminal/MacOsTerminal.css.ts
- apps/codeimage/src/components/Terminal/MacOsTerminal/MacOsTerminal.tsx
- apps/codeimage/src/components/Terminal/Tabs/TerminalWindowTabList.tsx
- apps/codeimage/src/components/Terminal/TerminalHost.tsx
- apps/codeimage/src/components/Terminal/WindowsTerminal/WindowsTerminal.css.ts
- apps/codeimage/src/components/Terminal/WindowsTerminal/WindowsTerminal.tsx
- apps/codeimage/src/components/Terminal/terminal.css.ts
- apps/codeimage/src/components/ThemeSwitcher/PresetSwitcher.tsx
- apps/codeimage/src/state/presets/bridge.ts
- apps/codeimage/src/state/presets/presets.ts
> feat: update preset

- apps/api/src/modules/preset/mapper/index.ts
- apps/api/src/modules/preset/schema/preset-create-dto.schema.ts
- apps/api/src/modules/preset/schema/preset-dto.schema.ts
- apps/api/test/__internal__/presetUtils.ts
- apps/api/test/helpers/seed.ts
- apps/api/test/modules/preset/handlers/create.test.ts
- apps/api/test/routes/v1/preset/create.integration.test.ts
- apps/api/test/routes/v1/preset/delete.integration.test.ts
- apps/api/test/routes/v1/preset/getAll.integration.test.ts
- apps/api/test/routes/v1/preset/getById.integration.test.ts
- apps/api/test/routes/v1/preset/update.integration.test.ts
- apps/codeimage/src/components/Presets/PresetPreview/PresetPreview.tsx
- apps/codeimage/src/components/Presets/PresetSwitcher/PresetSwitcher.tsx
- apps/codeimage/src/state/editor/editor.ts
- apps/codeimage/src/state/editor/frame.ts
- apps/codeimage/src/state/editor/terminal.ts
- apps/codeimage/src/state/presets/bridge.ts
- apps/codeimage/src/state/presets/presets.ts
- apps/codeimage/src/state/presets/types.ts
Typed preset `data` property in order to save the right structure and share types between frontend and backend
> feat: api preset data constraint

- apps/codeimage/package.json
- apps/codeimage/src/components/CustomEditor/CustomEditor.tsx
- apps/codeimage/src/components/CustomEditor/CustomEditorPreview.tsx
- apps/codeimage/src/components/Presets/PresetSwitcher/PresetSwitcher.tsx
- apps/codeimage/src/components/Presets/PresetUpdateDialog.tsx
- apps/codeimage/src/components/PropertyEditor/EditorStyleForm.tsx
- apps/codeimage/src/components/PropertyEditor/WindowStyleForm.tsx
- apps/codeimage/src/components/PropertyEditor/controls/CustomColorPicker.tsx
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- apps/codeimage/src/components/Toolbar/FrameToolbar.tsx
- apps/codeimage/src/components/Toolbar/SettingsDialog.tsx
- apps/codeimage/src/state/presets/presets.ts
- apps/codeimage/src/ui/ConfirmDialog/ConfirmDialog.tsx
- apps/codeimage/src/ui/ConfirmDialog/RenameContentDialog.tsx
- package.json
- pnpm-lock.yaml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: @codeui/kit@0.20.1 and kobalte 0.9.0 upgrade

- apps/codeimage/src/components/ThemeSwitcher/ThemeSwitcher.tsx
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- apps/codeimage/src/components/Toolbar/Toolbar.css.ts
- apps/codeimage/src/components/Toolbar/ToolbarSnippetName.tsx
- apps/codeimage/src/pages/Dashboard/components/ProjectToolbar/ProjectToolbar.tsx
- pnpm-lock.yaml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: refactor textfield with @codeui/kit

- apps/api/src/modules/preset/schema/preset-dto.schema.ts
- apps/codeimage/src/state/plugins/unique-id.ts
- apps/codeimage/src/state/presets/bridge.ts
- apps/codeimage/src/state/presets/types.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: preset local id sync missing

- apps/codeimage/src/components/CustomEditor/PreviewExportEditor.tsx
- apps/codeimage/src/components/Frame/Frame.css.ts
- apps/codeimage/src/components/Frame/PreviewFrame.tsx
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- apps/codeimage/src/components/Toolbar/ExportNewTabButton.tsx
- apps/codeimage/src/hooks/export-snippet.ts
- apps/codeimage/src/hooks/use-export-image.ts
- apps/codeimage/src/state/effects/onCopyToClipboard.tsx
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: fix export image rendering

- .changeset/fifty-socks-smash.md
- apps/codeimage/src/components/CustomEditor/CanvasEditor.tsx
- apps/codeimage/src/i18n/index.ts
- packages/ui/package.json
- packages/ui/src/lib/primitives/Snackbar/SnackbarHost.tsx
- pnpm-lock.yaml
* updated solid-toast to 0.5.0
> feat: optional format on paste event

- apps/codeimage/src/state/editor/createEditorSync.ts
- apps/codeimage/src/state/editor/frame.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: project loading issue

- .changeset/happy-tips-thank.md
- apps/codeimage/src/state/theme/themeRegistry.ts
- packages/highlight/package.json
- packages/highlight/src/lib/themes/fleetDark/dark.json
- packages/highlight/src/lib/themes/fleetDark/fleetDark.ts
- packages/highlight/src/lib/themes/fleetDark/index.ts
- packages/highlight/src/lib/themes/index.ts
> feat(app/highlight): add fleet theme

- .changeset/khaki-mirrors-listen.md
- apps/codeimage/src/state/editor/editor.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: add default font weight for local system fonts if not found

- .changeset/sharp-panthers-vanish.md
- packages/config/src/lib/base/languages.ts
> feat(config): yaml language support #618

- .changeset/tricky-kangaroos-relax.md
- apps/codeimage/src/components/Presets/PresetSwitcher/PresetSwitcher.tsx
- apps/codeimage/src/components/PropertyEditor/EditorStyleForm.tsx
- apps/codeimage/src/components/PropertyEditor/FrameStyleForm.tsx
- apps/codeimage/src/components/PropertyEditor/WindowStyleForm.tsx
- apps/codeimage/src/components/ThemeSwitcher/ThemeSwitcher.tsx
- apps/codeimage/src/components/Toolbar/ExportButton.tsx
- apps/codeimage/src/components/Toolbar/ExportNewTabButton.tsx
- apps/codeimage/src/components/Toolbar/SettingsDialog.tsx
- apps/codeimage/src/core/constants/umami.ts
- apps/codeimage/src/state/effects/onCopyToClipboard.tsx
- apps/codeimage/src/state/effects/onThemeChange.tsx
- apps/codeimage/src/state/version/version.store.ts
- apps/codeimage/src/umami.d.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat: update umami

- .changeset/sour-brooms-wash.md
- .github/actions/pnpm-install/action.yml
- packages/highlight/src/lib/themes/fleetDark/dark.json
- packages/highlight/src/lib/themes/fleetDark/fleetDark.ts
> fix: update fleet theme

- .changeset/wise-carrots-tie.md
- packages/config/src/lib/base/languages.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Add support for pascal programming language

- .changeset/shy-rabbits-travel.md
- apps/codeimage/src/state/theme/themeRegistry.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: 664 cant select xcode light and dark themes
